version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # pick your own strong secret in a local .env file (Compose reads it automatically)
      SECRET_KEY: ${SECRET_KEY:-dev-secret}
      DATABASE_URL: sqlite:///data/db.sqlite3
    volumes:
      - ./data:/app/data   # persist sqlite file outside the container
    restart: unless-stopped
