services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      # Named volume stores sqlite db outside the container FS
      - db-data:/app/data
    restart: unless-stopped

volumes:
  db-data:
